import type { EntityType } from './types';
import type { Lang } from '../i18n/site';

export type { Lang };

export interface ToolStrings {
  drop: string;
  choose: string;
  privacy: string;
  reading: string;
  extracting: string;
  modelLoading: string;
  modelNote: string;
  detecting: string;
  rendering: string;
  doneTitle: string;
  found: string;
  nothing: string;
  downloadPdf: string;
  downloadText: string;
  copyText: string;
  copied: string;
  again: string;
  error: string;
  notPdf: string;
  pages: string;
  typeNames: Record<EntityType, string>;
}

export const toolStrings: Partial<Record<Lang, ToolStrings>> = {
  en: {
    drop: 'Drop a PDF here, or click to choose a file',
    choose: 'Choose PDF',
    privacy: 'Your file is processed in your browser and is never uploaded.',
    reading: 'Reading file…',
    extracting: 'Reading the document…',
    modelLoading: 'Processing…',
    modelNote: 'The first run may take a moment — everything stays in your browser.',
    detecting: 'Finding sensitive data…',
    rendering: 'Applying redactions…',
    doneTitle: 'Done — data replaced',
    found: 'items replaced',
    nothing:
      'No sensitive data was detected automatically. Review the document yourself before sharing it.',
    downloadPdf: 'Download PDF',
    downloadText: 'Download text',
    copyText: 'Copy text',
    copied: 'Copied!',
    again: 'Redact another PDF',
    error: 'Something went wrong while processing this PDF. Please try another file.',
    notPdf: 'Please choose a PDF file.',
    pages: 'pages',
    typeNames: {
      PERSON: 'Names',
      ORG: 'Organisations',
      ADRESSE: 'Addresses',
      EMAIL: 'Emails',
      TELEFON: 'Phone numbers',
      IBAN: 'IBANs',
      CREDIT_CARD: 'Card numbers',
      SVNR: 'Social-security numbers',
      AKTENZEICHEN: 'Case numbers',
      FN: 'Company numbers',
      EZ: 'Land-register numbers',
      KENNZEICHEN: 'License plates',
      URL: 'URLs',
      IP: 'IP addresses',
      DATE: 'Dates',
    },
  },
  de: {
    drop: 'PDF hierher ziehen oder klicken, um eine Datei zu wählen',
    choose: 'PDF auswählen',
    privacy: 'Ihre Datei wird im Browser verarbeitet und niemals hochgeladen.',
    reading: 'Datei wird gelesen…',
    extracting: 'Dokument wird gelesen…',
    modelLoading: 'Wird verarbeitet…',
    modelNote: 'Der erste Durchlauf kann einen Moment dauern — alles bleibt in Ihrem Browser.',
    detecting: 'Sensible Daten werden gesucht…',
    rendering: 'Schwärzungen werden angewendet…',
    doneTitle: 'Fertig — Daten ersetzt',
    found: 'Einträge ersetzt',
    nothing:
      'Es wurden automatisch keine sensiblen Daten erkannt. Bitte prüfen Sie das Dokument selbst, bevor Sie es weitergeben.',
    downloadPdf: 'PDF herunterladen',
    downloadText: 'Text herunterladen',
    copyText: 'Text kopieren',
    copied: 'Kopiert!',
    again: 'Weiteres PDF schwärzen',
    error: 'Bei der Verarbeitung ist ein Fehler aufgetreten. Bitte versuchen Sie eine andere Datei.',
    notPdf: 'Bitte wählen Sie eine PDF-Datei.',
    pages: 'Seiten',
    typeNames: {
      PERSON: 'Namen',
      ORG: 'Organisationen',
      ADRESSE: 'Adressen',
      EMAIL: 'E-Mail-Adressen',
      TELEFON: 'Telefonnummern',
      IBAN: 'IBANs',
      CREDIT_CARD: 'Kartennummern',
      SVNR: 'SV-Nummern',
      AKTENZEICHEN: 'Aktenzeichen',
      FN: 'Firmenbuchnummern',
      EZ: 'Einlagezahlen',
      KENNZEICHEN: 'Kennzeichen',
      URL: 'URLs',
      IP: 'IP-Adressen',
      DATE: 'Datumsangaben',
    },
  },
  es: {
    drop: 'Suelta un PDF aquí o haz clic para elegir un archivo',
    choose: 'Elegir PDF',
    privacy: 'Tu archivo se procesa en tu navegador y nunca se sube.',
    reading: 'Leyendo el archivo…',
    extracting: 'Leyendo el documento…',
    modelLoading: 'Procesando…',
    modelNote: 'La primera vez puede tardar un momento; todo permanece en tu navegador.',
    detecting: 'Buscando datos sensibles…',
    rendering: 'Aplicando cambios…',
    doneTitle: 'Listo: datos sustituidos',
    found: 'elementos sustituidos',
    nothing:
      'No se detectaron datos sensibles automáticamente. Revisa el documento tú mismo antes de compartirlo.',
    downloadPdf: 'Descargar PDF',
    downloadText: 'Descargar texto',
    copyText: 'Copiar texto',
    copied: '¡Copiado!',
    again: 'Procesar otro PDF',
    error: 'Algo salió mal al procesar este PDF. Prueba con otro archivo.',
    notPdf: 'Elige un archivo PDF.',
    pages: 'páginas',
    typeNames: {
      PERSON: 'Nombres',
      ORG: 'Organizaciones',
      ADRESSE: 'Direcciones',
      EMAIL: 'Correos',
      TELEFON: 'Teléfonos',
      IBAN: 'IBAN',
      CREDIT_CARD: 'Tarjetas',
      SVNR: 'Números de seguridad social',
      AKTENZEICHEN: 'Números de expediente',
      FN: 'Números de empresa',
      EZ: 'Números registrales',
      KENNZEICHEN: 'Matrículas',
      URL: 'URLs',
      IP: 'Direcciones IP',
      DATE: 'Fechas',
    },
  },
  fr: {
    drop: 'Déposez un PDF ici ou cliquez pour choisir un fichier',
    choose: 'Choisir un PDF',
    privacy: 'Votre fichier est traité dans votre navigateur et n’est jamais envoyé.',
    reading: 'Lecture du fichier…',
    extracting: 'Lecture du document…',
    modelLoading: 'Traitement…',
    modelNote: 'La première fois peut prendre un instant ; tout reste dans votre navigateur.',
    detecting: 'Recherche des données sensibles…',
    rendering: 'Application des modifications…',
    doneTitle: 'Terminé : données remplacées',
    found: 'éléments remplacés',
    nothing:
      'Aucune donnée sensible détectée automatiquement. Vérifiez vous-même le document avant de le partager.',
    downloadPdf: 'Télécharger le PDF',
    downloadText: 'Télécharger le texte',
    copyText: 'Copier le texte',
    copied: 'Copié !',
    again: 'Traiter un autre PDF',
    error: 'Une erreur s’est produite lors du traitement de ce PDF. Essayez un autre fichier.',
    notPdf: 'Veuillez choisir un fichier PDF.',
    pages: 'pages',
    typeNames: {
      PERSON: 'Noms',
      ORG: 'Organisations',
      ADRESSE: 'Adresses',
      EMAIL: 'E-mails',
      TELEFON: 'Téléphones',
      IBAN: 'IBAN',
      CREDIT_CARD: 'Cartes',
      SVNR: 'Numéros de sécurité sociale',
      AKTENZEICHEN: 'Numéros de dossier',
      FN: 'Numéros d’entreprise',
      EZ: 'Numéros de registre foncier',
      KENNZEICHEN: 'Plaques d’immatriculation',
      URL: 'URL',
      IP: 'Adresses IP',
      DATE: 'Dates',
    },
  },
  it: {
    drop: 'Trascina un PDF qui o clicca per scegliere un file',
    choose: 'Scegli PDF',
    privacy: 'Il tuo file è elaborato nel browser e non viene mai caricato.',
    reading: 'Lettura del file…',
    extracting: 'Lettura del documento…',
    modelLoading: 'Elaborazione…',
    modelNote: 'La prima volta può richiedere un momento; tutto resta nel tuo browser.',
    detecting: 'Ricerca dei dati sensibili…',
    rendering: 'Applicazione delle modifiche…',
    doneTitle: 'Fatto: dati sostituiti',
    found: 'elementi sostituiti',
    nothing:
      'Nessun dato sensibile rilevato automaticamente. Controlla tu stesso il documento prima di condividerlo.',
    downloadPdf: 'Scarica PDF',
    downloadText: 'Scarica testo',
    copyText: 'Copia testo',
    copied: 'Copiato!',
    again: 'Elabora un altro PDF',
    error: 'Qualcosa è andato storto durante l’elaborazione di questo PDF. Prova un altro file.',
    notPdf: 'Scegli un file PDF.',
    pages: 'pagine',
    typeNames: {
      PERSON: 'Nomi',
      ORG: 'Organizzazioni',
      ADRESSE: 'Indirizzi',
      EMAIL: 'E-mail',
      TELEFON: 'Telefoni',
      IBAN: 'IBAN',
      CREDIT_CARD: 'Carte',
      SVNR: 'Numeri di previdenza sociale',
      AKTENZEICHEN: 'Numeri di pratica',
      FN: 'Numeri di impresa',
      EZ: 'Numeri catastali',
      KENNZEICHEN: 'Targhe',
      URL: 'URL',
      IP: 'Indirizzi IP',
      DATE: 'Date',
    },
  },
  pt: {
    drop: 'Arraste um PDF para aqui ou clique para escolher um ficheiro',
    choose: 'Escolher PDF',
    privacy: 'O seu ficheiro é processado no navegador e nunca é carregado.',
    reading: 'A ler o ficheiro…',
    extracting: 'A ler o documento…',
    modelLoading: 'A processar…',
    modelNote: 'A primeira vez pode demorar um momento; tudo permanece no seu navegador.',
    detecting: 'A procurar dados sensíveis…',
    rendering: 'A aplicar as alterações…',
    doneTitle: 'Concluído: dados substituídos',
    found: 'elementos substituídos',
    nothing:
      'Não foram detetados dados sensíveis automaticamente. Verifique o documento antes de o partilhar.',
    downloadPdf: 'Descarregar PDF',
    downloadText: 'Descarregar texto',
    copyText: 'Copiar texto',
    copied: 'Copiado!',
    again: 'Processar outro PDF',
    error: 'Algo correu mal ao processar este PDF. Tente outro ficheiro.',
    notPdf: 'Escolha um ficheiro PDF.',
    pages: 'páginas',
    typeNames: {
      PERSON: 'Nomes',
      ORG: 'Organizações',
      ADRESSE: 'Moradas',
      EMAIL: 'E-mails',
      TELEFON: 'Telefones',
      IBAN: 'IBAN',
      CREDIT_CARD: 'Cartões',
      SVNR: 'Números de segurança social',
      AKTENZEICHEN: 'Números de processo',
      FN: 'Números de empresa',
      EZ: 'Números prediais',
      KENNZEICHEN: 'Matrículas',
      URL: 'URLs',
      IP: 'Endereços IP',
      DATE: 'Datas',
    },
  },
  nl: {
    drop: 'Sleep een PDF hierheen of klik om een bestand te kiezen',
    choose: 'PDF kiezen',
    privacy: 'Je bestand wordt in je browser verwerkt en nooit geüpload.',
    reading: 'Bestand lezen…',
    extracting: 'Document lezen…',
    modelLoading: 'Bezig met verwerken…',
    modelNote: 'De eerste keer kan even duren; alles blijft in je browser.',
    detecting: 'Gevoelige gegevens zoeken…',
    rendering: 'Wijzigingen toepassen…',
    doneTitle: 'Klaar: gegevens vervangen',
    found: 'items vervangen',
    nothing:
      'Er zijn automatisch geen gevoelige gegevens gedetecteerd. Controleer het document zelf voordat je het deelt.',
    downloadPdf: 'PDF downloaden',
    downloadText: 'Tekst downloaden',
    copyText: 'Tekst kopiëren',
    copied: 'Gekopieerd!',
    again: 'Nog een PDF verwerken',
    error: 'Er ging iets mis bij het verwerken van deze PDF. Probeer een ander bestand.',
    notPdf: 'Kies een PDF-bestand.',
    pages: 'pagina’s',
    typeNames: {
      PERSON: 'Namen',
      ORG: 'Organisaties',
      ADRESSE: 'Adressen',
      EMAIL: 'E-mails',
      TELEFON: 'Telefoons',
      IBAN: 'IBANs',
      CREDIT_CARD: 'Kaarten',
      SVNR: 'Burgerservicenummers',
      AKTENZEICHEN: 'Dossiernummers',
      FN: 'Bedrijfsnummers',
      EZ: 'Kadasternummers',
      KENNZEICHEN: 'Kentekens',
      URL: 'URLs',
      IP: 'IP-adressen',
      DATE: 'Datums',
    },
  },
  ar: {
    drop: 'أسقط ملف PDF هنا أو انقر لاختيار ملف',
    choose: 'اختر PDF',
    privacy: 'تتم معالجة ملفك في متصفحك ولا يُرفع أبدًا.',
    reading: 'جارٍ قراءة الملف…',
    extracting: 'جارٍ قراءة المستند…',
    modelLoading: 'جارٍ المعالجة…',
    modelNote: 'قد تستغرق المرة الأولى لحظة؛ يبقى كل شيء في متصفحك.',
    detecting: 'جارٍ البحث عن البيانات الحساسة…',
    rendering: 'جارٍ تطبيق التغييرات…',
    doneTitle: 'تم: استُبدلت البيانات',
    found: 'عناصر مستبدلة',
    nothing: 'لم تُكتشف بيانات حساسة تلقائيًا. راجع المستند بنفسك قبل مشاركته.',
    downloadPdf: 'تنزيل PDF',
    downloadText: 'تنزيل النص',
    copyText: 'نسخ النص',
    copied: 'تم النسخ!',
    again: 'معالجة ملف PDF آخر',
    error: 'حدث خطأ أثناء معالجة هذا الملف. جرّب ملفًا آخر.',
    notPdf: 'يرجى اختيار ملف PDF.',
    pages: 'صفحات',
    typeNames: {
      PERSON: 'الأسماء',
      ORG: 'المنظمات',
      ADRESSE: 'العناوين',
      EMAIL: 'البريد الإلكتروني',
      TELEFON: 'الهواتف',
      IBAN: 'IBAN',
      CREDIT_CARD: 'البطاقات',
      SVNR: 'أرقام الضمان الاجتماعي',
      AKTENZEICHEN: 'أرقام القضايا',
      FN: 'أرقام الشركات',
      EZ: 'أرقام السجل العقاري',
      KENNZEICHEN: 'لوحات السيارات',
      URL: 'الروابط',
      IP: 'عناوين IP',
      DATE: 'التواريخ',
    },
  },
  lv: {
    drop: 'Velciet PDF šeit vai noklikšķiniet, lai izvēlētos failu',
    choose: 'Izvēlēties PDF',
    privacy: 'Jūsu fails tiek apstrādāts pārlūkā un nekad netiek augšupielādēts.',
    reading: 'Lasa failu…',
    extracting: 'Lasa dokumentu…',
    modelLoading: 'Apstrādā…',
    modelNote: 'Pirmo reizi var aizņemt mirkli; viss paliek jūsu pārlūkā.',
    detecting: 'Meklē jutīgos datus…',
    rendering: 'Piemēro izmaiņas…',
    doneTitle: 'Gatavs: dati aizstāti',
    found: 'aizstāti vienumi',
    nothing: 'Automātiski netika atrasti jutīgi dati. Pirms kopīgošanas pārbaudiet dokumentu pats.',
    downloadPdf: 'Lejupielādēt PDF',
    downloadText: 'Lejupielādēt tekstu',
    copyText: 'Kopēt tekstu',
    copied: 'Nokopēts!',
    again: 'Apstrādāt citu PDF',
    error: 'Apstrādājot šo PDF, radās kļūda. Mēģiniet citu failu.',
    notPdf: 'Lūdzu, izvēlieties PDF failu.',
    pages: 'lapas',
    typeNames: {
      PERSON: 'Vārdi',
      ORG: 'Organizācijas',
      ADRESSE: 'Adreses',
      EMAIL: 'E-pasti',
      TELEFON: 'Tālruņi',
      IBAN: 'IBAN',
      CREDIT_CARD: 'Kartes',
      SVNR: 'Sociālās apdrošināšanas numuri',
      AKTENZEICHEN: 'Lietu numuri',
      FN: 'Uzņēmumu numuri',
      EZ: 'Zemesgrāmatu numuri',
      KENNZEICHEN: 'Numura zīmes',
      URL: 'URL',
      IP: 'IP adreses',
      DATE: 'Datumi',
    },
  },
  zh: {
    drop: '将 PDF 拖到此处，或点击选择文件',
    choose: '选择 PDF',
    privacy: '你的文件在浏览器中处理，绝不上传。',
    reading: '正在读取文件…',
    extracting: '正在读取文档…',
    modelLoading: '正在处理…',
    modelNote: '仅首次会稍候片刻；所有内容都保留在你的浏览器中。',
    detecting: '正在查找敏感数据…',
    rendering: '正在应用更改…',
    doneTitle: '完成：数据已替换',
    found: '项已替换',
    nothing: '未自动检测到敏感数据。分享前请自行检查文档。',
    downloadPdf: '下载 PDF',
    downloadText: '下载文本',
    copyText: '复制文本',
    copied: '已复制！',
    again: '处理另一个 PDF',
    error: '处理此 PDF 时出错。请尝试其他文件。',
    notPdf: '请选择一个 PDF 文件。',
    pages: '页',
    typeNames: {
      PERSON: '姓名',
      ORG: '组织',
      ADRESSE: '地址',
      EMAIL: '邮箱',
      TELEFON: '电话',
      IBAN: 'IBAN',
      CREDIT_CARD: '银行卡',
      SVNR: '社保号',
      AKTENZEICHEN: '案件编号',
      FN: '公司编号',
      EZ: '不动产登记号',
      KENNZEICHEN: '车牌',
      URL: '网址',
      IP: 'IP 地址',
      DATE: '日期',
    },
  },
};
